import "package:example/models/product.dart";

class ProductService {
  static List<Product> getMockProducts() => [
    Product(
      id: "p1",
      name: "Smartphone X",
      description: "Latest model smartphone with AI features.",
      price: 799.99,
      stock: 50,
      tags: ["electronics", "mobile", "new"],
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      isActive: true,
      category: "Electronics",
    ),
    Product(
      id: "p2",
      name: "Laptop Pro 13",
      description: "High performance laptop for professionals.",
      price: 1200,
      stock: 20,
      tags: ["electronics", "computer", "premium"],
      createdAt: DateTime.now().subtract(const Duration(days: 40)),
      isActive: true,
      category: "Electronics",
    ),
    Product(
      id: "p3",
      name: "Bluetooth Speaker",
      description: "Portable audio device with rich bass.",
      price: 89.99,
      stock: 100,
      tags: ["audio", "sale", "portable"],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      isActive: true,
      category: "Audio",
    ),
    Product(
      id: "p4",
      name: "Mechanical Keyboard",
      description: "Durable gaming keyboard with RGB lighting.",
      price: 119.50,
      stock: 15,
      tags: ["computer", "gaming", "peripherals"],
      createdAt: DateTime.now().subtract(const Duration(days: 70)),
      isActive: false,
      // Inactive product
      category: "Peripherals",
    ),
    Product(
      id: "p5",
      name: "Smartwatch Lite",
      description: "Fitness tracker and smartwatch with heart rate monitor.",
      price: 199.99,
      stock: 75,
      tags: ["wearable", "electronics", "new", "fitness"],
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      isActive: true,
      category: "Wearables",
    ),
    Product(
      id: "p6",
      name: "Wireless Mouse",
      description: "Ergonomic wireless mouse for daily use.",
      price: 25,
      stock: 200,
      tags: ["computer", "peripherals"],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      isActive: true,
      category: "Peripherals",
    ),
    Product(
      id: "p7",
      name: '4K Monitor 27"',
      description: "High resolution display for work and entertainment.",
      price: 349,
      stock: 30,
      tags: ["electronics", "display", "premium"],
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      isActive: true,
      category: "Electronics",
    ),
    Product(
      id: "p8",
      name: "USB-C Hub",
      description: "Multiport adapter for laptops and devices.",
      price: 49.99,
      stock: 150,
      tags: ["accessories", "connectivity"],
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
      isActive: true,
      category: "Accessories",
    ),
    Product(
      id: "p9",
      name: "Gaming Headset",
      description: "Immersive audio for gaming sessions.",
      price: 75,
      stock: 40,
      tags: ["audio", "gaming", "peripherals"],
      createdAt: DateTime.now().subtract(const Duration(days: 25)),
      isActive: true,
      category: "Audio",
    ),
    Product(
      id: "p10",
      name: "Portable SSD 1TB",
      description: "Fast external storage for large files.",
      price: 150,
      stock: 60,
      tags: ["storage", "new", "portable"],
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      isActive: true,
      category: "Storage",
    ),
    Product(
      id: "p11",
      name: "Old Broken Phone",
      description: "For parts only, not functional.",
      price: 5,
      stock: 0,
      // Out of stock
      tags: ["junk", "broken"],
      createdAt: DateTime.now().subtract(const Duration(days: 300)),
      isActive: false,
      // Inactive product
      category: "Junk",
    ),
    Product(
      id: "p12",
      name: "Webcam HD",
      description: "High definition webcam for video calls.",
      price: 35,
      stock: 80,
      tags: ["computer", "accessories"],
      createdAt: DateTime.now().subtract(const Duration(days: 120)),
      isActive: true,
      category: "Peripherals",
    ),
    Product(
      id: "p13",
      name: "Smart Plug",
      description: "Control your appliances remotely.",
      price: 15,
      stock: 200,
      tags: ["smart home", "electronics"],
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
      isActive: true,
      category: "Smart Home",
    ),
  ];
}
